info:
  author: huss
  date: 2024年07月02日
  remark: rule-test
  my-server-name: rule-test

spring:
  application:
    name: ${info.my-server-name}
  profiles:
    active: @profileActive@
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      enable: true
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    suffix: .ftl               #指定Freemarker模板文件的后缀名

  # 远端配置
  config:
    import:
      - optional:nacos:${spring.cloud.nacos.config.prefix}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?preference=remote
  #nacos配置
  cloud:
    config:
      discovery:
        enabled: true
    discovery:
      enabled: false
    nacos:
      config:
        server-addr: @nacos.addr@ #nacos中心地址
        file-extension: yaml # 配置文件格式
        prefix: config
        namespace: rule_test
        username: nacos
        password: zhyx1202
        group: DEFAULT_GROUP
        encode: UTF-8
        enabled: true
        preference: remote
# 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

# openapi 文档配置
springdoc:
  version: 1.0.0
  name: 规则自动化测试接口文档
  description: 规则自动化测试接口文档
  url: http://localhost:${server.port}${server.servlet.context-path}/doc.html
  groups:
    - group: api
      # 多个,分割
      packagesToScan: com.coral.test.rule.controller
      # 多个,分割
      packagesToExclude:
      tags:
        - name: 1.0.0
          desc: 测试


